export const OBSERVATION_CATEGORIES = [
  {
    label: 'ROCK INSTABILITY',
    items: [
      { label: 'Loose Blocks', phrase: 'Loose blocks present.', risk: 'High' },
      { label: 'Rockfall Debris', phrase: 'Rockfall debris observed.', risk: 'High' },
      { label: 'Overhang', phrase: 'Overhang identified.', risk: 'High' },
      { label: 'Detached Block', phrase: 'Detached block noted.', risk: 'High' },
      { label: 'Wedge Formation', phrase: 'Wedge formation observed.', risk: 'High' },
      { label: 'Planar Sliding Surface', phrase: 'Planar sliding surface visible.', risk: 'High' },
      { label: 'Toppling Blocks', phrase: 'Toppling blocks observed.', risk: 'High' },
      { label: 'Open Joint', phrase: 'Open joint identified.', risk: 'High' },
      { label: 'Rock Spalling', phrase: 'Rock spalling noted.', risk: 'High' },
    ],
  },
  {
    label: 'STRUCTURAL FEATURES',
    items: [
      { label: 'Persistent Joint', phrase: 'Persistent joint observed.' },
      { label: 'Closely Spaced Joints', phrase: 'Closely spaced joints noted.' },
      { label: 'Widely Spaced Joints', phrase: 'Widely spaced joints observed.' },
      { label: 'Joint Infilling', phrase: 'Joint infilling noted.' },
      { label: 'Clay Filled Joint', phrase: 'Clay filled joint observed.' },
      { label: 'Fault Zone', phrase: 'Fault zone identified.' },
      { label: 'Highly Fractured Zone', phrase: 'Highly fractured zone noted.' },
      { label: 'Brecciated Rock', phrase: 'Brecciated rock observed.' },
    ],
  },
  {
    label: 'WEATHERING',
    items: [
      { label: 'Fresh Rock', phrase: 'Fresh rock.' },
      { label: 'Slightly Weathered Rock', phrase: 'Slightly weathered rock.' },
      { label: 'Moderately Weathered Rock', phrase: 'Moderately weathered rock.' },
      { label: 'Highly Weathered Rock', phrase: 'Highly weathered rock.' },
      { label: 'Completely Weathered Rock', phrase: 'Completely weathered rock.' },
      { label: 'Saprolite', phrase: 'Saprolite.' },
      { label: 'Residual Soil', phrase: 'Residual soil.' },
      { label: 'Colluvium', phrase: 'Colluvium.' },
    ],
  },
  {
    label: 'GROUNDWATER',
    items: [
      { label: 'Dry Surface', phrase: 'Surface is dry.' },
      { label: 'Damp Surface', phrase: 'Surface is damp.' },
      { label: 'Wet Patch', phrase: 'Wet patch observed.', risk: 'Medium' },
      { label: 'Seepage', phrase: 'Seepage observed.', risk: 'Medium' },
      { label: 'Dripping Water', phrase: 'Dripping water noted.' },
      { label: 'Flowing Water', phrase: 'Flowing water observed.' },
      { label: 'Groundwater Inflow', phrase: 'Groundwater inflow noted.' },
      { label: 'Blocked Drain', phrase: 'Blocked drain observed.' },
    ],
  },
  {
    label: 'SLOPE CONDITION',
    items: [
      { label: 'Surface Erosion', phrase: 'Surface erosion observed.', risk: 'Medium' },
      { label: 'Scour', phrase: 'Scour noted.', risk: 'Medium' },
      { label: 'Undercutting', phrase: 'Undercutting observed.' },
      { label: 'Tension Crack', phrase: 'Tension crack identified.', risk: 'Medium' },
      { label: 'Settlement', phrase: 'Settlement noted.' },
      { label: 'Slope Bulging', phrase: 'Slope bulging observed.' },
      { label: 'Toe Instability', phrase: 'Toe instability noted.' },
    ],
  },
  {
    label: 'SUPPORT CONDITION',
    items: [
      { label: 'Mesh Damage', phrase: 'Mesh damage observed.' },
      { label: 'Bolt Head Missing', phrase: 'Bolt head missing.' },
      { label: 'Bolt Plate Loose', phrase: 'Bolt plate loose.' },
      { label: 'Shotcrete Cracking', phrase: 'Shotcrete cracking noted.' },
      { label: 'Shotcrete Spalling', phrase: 'Shotcrete spalling observed.' },
      { label: 'Drain Blocked', phrase: 'Drain blocked.' },
      { label: 'Support Corrosion', phrase: 'Support corrosion observed.' },
    ],
  },
];
