export const SOIL_OBSERVATION_CATEGORIES = [
  {
    label: 'SOIL TYPE',
    items: [
      { label: 'Clay', phrase: 'Clay observed.' },
      { label: 'Silt', phrase: 'Silt observed.' },
      { label: 'Sand', phrase: 'Sand observed.' },
      { label: 'Gravel', phrase: 'Gravel observed.' },
      { label: 'Fill', phrase: 'Fill material observed.' },
      { label: 'Residual Soil', phrase: 'Residual soil observed.' },
      { label: 'Colluvium', phrase: 'Colluvium observed.' },
      { label: 'Alluvium', phrase: 'Alluvium observed.' },
    ],
  },
  {
    label: 'CONSISTENCY / DENSITY',
    items: [
      { label: 'Very Soft', phrase: 'Very soft consistency.' },
      { label: 'Soft', phrase: 'Soft consistency.' },
      { label: 'Firm', phrase: 'Firm consistency.' },
      { label: 'Stiff', phrase: 'Stiff consistency.' },
      { label: 'Very Stiff', phrase: 'Very stiff consistency.' },
      { label: 'Hard', phrase: 'Hard consistency.' },
      { label: 'Very Loose', phrase: 'Very loose density.' },
      { label: 'Loose', phrase: 'Loose density.' },
      { label: 'Medium Dense', phrase: 'Medium dense.' },
      { label: 'Dense', phrase: 'Dense.' },
      { label: 'Very Dense', phrase: 'Very dense.' },
    ],
  },
  {
    label: 'MOISTURE / GROUNDWATER',
    items: [
      { label: 'Dry', phrase: 'Dry condition.' },
      { label: 'Moist', phrase: 'Moist condition.' },
      { label: 'Wet', phrase: 'Wet condition.' },
      { label: 'Saturated', phrase: 'Saturated condition.' },
      { label: 'Seepage', phrase: 'Seepage observed.' },
      { label: 'Perched Water', phrase: 'Perched water table observed.' },
      { label: 'Water Table Above Base', phrase: 'Water table observed above base.' },
    ],
  },
  {
    label: 'SURFACE / MATERIAL CONDITION',
    items: [
      { label: 'Softening', phrase: 'Softening observed.', risk: 'Medium' },
      { label: 'Slaking', phrase: 'Slaking observed.', risk: 'Medium' },
      { label: 'Erosion', phrase: 'Erosion observed.', risk: 'Medium' },
      { label: 'Piping', phrase: 'Piping observed.', risk: 'High' },
      { label: 'Cracking', phrase: 'Cracking observed.', risk: 'Medium' },
      { label: 'Settlement Observed', phrase: 'Settlement observed.', risk: 'High' },
      { label: 'Bulging', phrase: 'Bulging observed.', risk: 'High' },
      { label: 'Toe Softening', phrase: 'Toe softening observed.', risk: 'Medium' },
      { label: 'Rutting', phrase: 'Rutting observed.' },
      { label: 'Ponding', phrase: 'Ponding observed.' },
    ],
  },
  {
    label: 'RETAINING / EXCAVATION INDICATORS',
    items: [
      { label: 'Wall Cracking', phrase: 'Wall cracking observed.', risk: 'High' },
      { label: 'Wall Movement', phrase: 'Wall movement observed.', risk: 'High' },
      { label: 'Backfill Saturation', phrase: 'Backfill saturation observed.', risk: 'High' },
      { label: 'Surcharge Present', phrase: 'Surcharge present.' },
      { label: 'Drainage Blocked', phrase: 'Drainage blocked.', risk: 'Medium' },
      { label: 'Toe Erosion', phrase: 'Toe erosion observed.', risk: 'Medium' },
      { label: 'Local Slumping', phrase: 'Local slumping observed.', risk: 'High' },
    ],
  },
];
